# Generated by Django 3.2.8 on 2021-11-02 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='getintouch',
            old_name='Name',
            new_name='Title',
        ),
    ]
