# Generated by Django 3.2.8 on 2021-11-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_rename_name_getintouch_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getintouch',
            name='Title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
