# Generated by Django 3.2.8 on 2021-11-02 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_getintouch_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getintouch',
            name='Email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='getintouch',
            name='Number',
            field=models.IntegerField(null=True),
        ),
    ]
