# Generated by Django 3.2.8 on 2021-11-02 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_blogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Coffee_image', models.ImageField(upload_to='static/images')),
                ('Description', models.CharField(max_length=60)),
                ('Cost', models.FloatField()),
                ('Discounted_Cost', models.FloatField()),
            ],
        ),
    ]
