# Generated by Django 3.2.8 on 2021-11-04 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_menu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='Description',
            new_name='Coffee_name',
        ),
    ]
