# Generated by Django 3.2.8 on 2021-11-15 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20211115_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='Images',
            field=models.ImageField(upload_to='./backend/static/images/'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='Coffee_image',
            field=models.ImageField(upload_to='./backend/static/images/'),
        ),
    ]
