# Generated by Django 3.2.8 on 2022-02-21 20:24

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_auto_20220221_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='Images',
            field=models.ImageField(default=' ', upload_to=backend.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='menu',
            name='Coffee_image',
            field=models.ImageField(default=' ', upload_to=backend.models.user_directory_path),
        ),
    ]
